name: CD Front-end

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  ci:
    name: CI Workflow Main
    uses: ./.github/workflows/ci-frontend-main.yml

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js $
        uses: actions/setup-node@v1
        with:
          node-version: "18.12.1"
      - name: Instalação do cliente Railway
        working-directory: front-end/
        run: npm install -g @railway/cli

      - name: Cache dist get
        id: cache-dist-get
        uses: actions/cache@v3
        env:
          cache-name: cache-front-dist
        with:
          path: front-end/dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Deploy
        working-directory: front-end/dist
        run: railway up --detach --service sgcm-msc-front
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_FRONT }}
