name: CD Front-end

on:
#   schedule:
#     - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  ci:
    name: CI Workflow Main
    uses: ./.github/workflows/ci-frontend-main.yml

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js $
        uses: actions/setup-node@v1
        with:
          node-version: "18.12.1"
      - name: Instalação do cliente Railway
        working-directory: front-end/
        run: npm install -g @railway/cli

      - name: Restaurar cache
        uses: actions/cache@v3
        with:
          path: front-end/dist
          key: build-${{ github.sha }}

      - name: Deploy
        working-directory: front-end/dist/sgcmapp
        run: railway up --detach --service sgcm-msc-front
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_FRONT }}
