name: CI Front-end

on:
  push:
    branches:
      - "main"
    paths:
      - "front-end/**"
  pull_request:
    paths:
      - "front-end/**"
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use NodE
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"
      - name: Install packages with NPM
        working-directory: front-end/
        run: npm install
      - name: Test
        working-directory: front-end/
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"
      - name: Install packages with NPM
        working-directory: front-end/
        run: npm install
      - name: Test
        working-directory: front-end/
        run: npm run build --prod
      - name: Cache dist
        uses: actions/cache@v3
        with:
          path: front-end/dist
          key: build-${{ github.sha }}
